### PR TITLE
Add dev configuration for config split

### PR DESCRIPTION
**Pull request by doxigo**
Assuming the `dev` naming convention, I'd say we should also include this in local.settings.php

### CODE REVIEW

**Comment by esolitos** [comment]
There was a discussion going on a few weeks ago that we should probably setup the configuration splits in this way:

- A _dev/local_ split named **"Environment: Dev"** (machine: `environment_dev`) which is **enabled** by default.
- A _production_ split **"Environment: Prod"** (machine: `environment_prod`) which is **disabled** by default and is enabled in the production settings file.

The reason for this is that most of the times _(by definition)_ the project will be in a _non-production_ environment, so it makes more sense to **assume that it the environment is not production** keep the relative split disabled.
This has some side-effects:
- **A positive** one is that a freshly cloned repository is ready-to-use by any developers, without the need to remember to change anything.
- But **a negative** effect is that if someone wants to do changes directly on the Prod instance, and sync the configuration in the repository by getting the database locally and running `config-export`, They will also need to remember to switch on the production split. Worth notice that _we collectively highly discourage_ this workflow, so this side-effect should be mitigated by the fact that we do this relatively rarely.

@szeidler @mnlund What is your take on this?

**Comment by doxigo** [comment]
@esolitos good points made, but I'd suggest to keep the machine name to simple things as `dev`, `staging` & `prod`, since at some point we'll probably mess up the dictation of `environment` when creating a config split (or just forget to use the prefix)

but I'm down with both, as you guys prefer

**Comment by esolitos** [comment]
🤔  _"someone making a typo"_ is not a good reason to not use a term imho.

Also, to further mitigate the higlighted issue, if we go that way we could already provide a `ramsalt/meta-environments` package which takes care of this.

**Comment by doxigo** [comment]
a `meta` package sounds good as well

**Comment by esolitos** [comment]
I suggest waiting for @szeidler and possibly @mnlund review here.

**Comment by szeidler** [comment]
Did it became obsolete? Why is it closed @esolitos ?

**Pull request closed without merging**
